---
title: "R Notebook"
output: html_notebook
---

#Get genome/packages/functions

```{r load, message=FALSE, warning=FALSE, paged.print=TRUE}
source("packages.R")

Arath_Genome <- getGenomeDnaStringSet("Arabidopsis thaliana")

print(alphabetFrequency(DNAString("CACTACAA")))
```


#Generating random sequences

```{r generate seqs, message=FALSE, warning=FALSE}
seqnum <- 100
seqlen <- 8

library(universalmotif)
randseqs <- create_sequences(alphabet = "DNA",
                             seqnum = seqnum, 
                             seqlen = seqlen,
                             monofreqs = c(A = 4, C = 3, G = 0, T = 1)) #from frequencies above

DNAString("CACTACAA") %in% randseqs #should be false
```


#Test vs algorithm (TIR/TSD filtering only) and time - run on 13/SEP/19

```{r run algorithm}
packsFound <- vector("integer", seqnum)

start = Sys.time()

for(i in 1:seqnum) {
  packsFound[i] <- packSearch(randseqs[[i]],
                           Arath_Genome, 
                           mismatch = 0, 
                           element.length = c(300, 3500), 
                           TSD.length = 3) %>%
    count() %>%
    unlist()
}

end = Sys.time()
```

#Results

```{r get results}
print("Total matches found per search")
sum(packsFound) / seqnum

print("Time taken")
print(end-start) #will be slightly slower than expected due to collation of results

hist(packsFound)
abline(v = 8)
```

