#' @title Identify Terminal Inverted Repeat Matches
#' @description Searches a DNAStringSet for potential TIRs based on sequence similarity.
#' @param subSeq A \code{\link[Biostrings]{DNAString}} object to be searched for.
#' @param Genome A \code{\link[Biostrings]{DNAStringSet}} object containing the DNAString objects to be searched.
#' @param mismatch The allowable mismatch between \code{subSeq} and a given slice of \code{Genome}. Includes indels.
#' @param strand The directionality of the search string ("+", "-" or "*").
#' @author Jack Gisby
#' @details
#' Called by \code{\link{packSearch}}. Used by \code{\link{packSearch}} as an initial filtering stage. \code{\link[Biostrings]{matchPattern}} from Biostrings is used for pattern matching. It is recommended to use the general pipeline function \code{\link{packSearch}} for identification of potential pack elements, however each stage may be called individually.
#' @return A dataframe, \code{tirMatches}, containing identified matches. Will be appended to \code{tirMatches} if given. The dataframe is in the format generated by \code{\link[GenomicRanges]{makeGRangesFromDataFrame}}.
#' @export

identifyTirMatches <- function(subSeq,
                               Genome,
                               mismatch = 0,
                               strand = "*") {
  tirMatches <- data.frame(
    seqnames = character(),
    start = integer(),
    end = integer(),
    width = integer(),
    strand = factor()
  )

  for (i in 1:length(Genome)) {
    matches <- Biostrings::matchPattern(subSeq,
      Genome[[i]],
      max.mismatch = mismatch,
      with.indels = TRUE
    )

    if (length(matches) > 0) {
      tirMatches <- rbind(tirMatches, data.frame(
        seqnames = names(Genome)[i],
        start = matches@ranges@start,
        end = matches@ranges@start + matches@ranges@width - 1,
        width = matches@ranges@width,
        strand = strand
      ))
    }
  }

  return(tirMatches)
}
