#' @title
#' Identify Terminal Inverted Repeat Matches
#'
#' @description
#' Searches a \code{\link[Biostrings:XStringSet-class]{DNAStringSet}} 
#' for potential TIRs based on sequence similarity.
#'
#' @param tirSeq 
#' A \code{\link[Biostrings:DNAString-class]{DNAString}} 
#' object to be searched for.
#'
#' @param Genome
#' A \code{\link[Biostrings:XStringSet-class]{DNAStringSet}} 
#' object containing the 
#' \code{\link[Biostrings:DNAString-class]{DNAString}} 
#' objects to be searched.
#'
#' @param mismatch
#' The allowable mismatch between \code{tirSeq} and a 
#' given slice of \code{Genome}. Includes indels.
#'
#' @param strand
#' The directionality of the search string ("+", "-" or "*").
#'
#' @param tsdLength
#' Integer referring to the length of the flanking TSD region.
#'
#' @details 
#' Called by \code{\link{packSearch}}. Used by 
#' \code{\link{packSearch}} as an initial filtering stage. 
#' \code{\link[Biostrings]{matchPattern}} from Biostrings 
#' is used for pattern matching. It is recommended to use 
#' the general pipeline function \code{\link{packSearch}} 
#' for identification of potential pack elements, however 
#' each stage may be called individually.
#'
#' @return
#' A dataframe, \code{tirMatches}, containing identified 
#' matches. The dataframe is in the format generated by 
#' \code{\link{packSearch}}.
#' 
#' @seealso 
#' \code{\link[Biostrings:XStringSet-class]{DNAStringSet}},
#' \code{\link{packSearch}}, \code{\link[Biostrings]{matchPattern}},
#' \code{\link[Biostrings:DNAString-class]{DNAString}} 
#' 
#' @examples
#' data(arabidopsisThalianaRefseq)
#' 
#' forwardMatches <- identifyTirMatches(
#'     Biostrings::DNAString("CACTACAA"),
#'     arabidopsisThalianaRefseq,
#'     tsdLength = 3
#' )
#' 
#' @author
#' Jack Gisby
#'
#' @export

identifyTirMatches <- function(tirSeq, Genome, mismatch = 0, strand = "*", 
                            tsdLength) {
    if (strand != "-" & strand != "+" & strand != "*") {
        stop("Argument 'strand' must be specified as '-', '+' or '*'")
    }

    tirMatches <- data.frame(
        seqnames = factor(),
        start = integer(),
        end = integer(),
        width = integer(),
        strand = factor()
    )

    for (i in seq_len(length(Genome))) {
        matches <- Biostrings::matchPattern(tirSeq,
            Genome[[i]],
            max.mismatch = mismatch,
            with.indels = TRUE
        )

        if (length(matches) > 0) {
            tirMatches <- rbind(tirMatches, data.frame(
                seqnames = names(Genome)[i],
                start = matches@ranges@start,
                end = matches@ranges@start + matches@ranges@width - 1,
                width = matches@ranges@width,
                strand = strand
            ))
        }
    }

    if (strand == "-") {
        removeMatch <- mapply(function(end, seqnames, tsdLength, Genome) {
                seq <- Genome[Genome@ranges@NAMES == seqnames][[1]]
                return((end + tsdLength) > seq@length)
            },
            tirMatches$end,
            tirMatches$seqnames,
            MoreArgs = list(tsdLength, Genome)
        )
        tirMatches <- tirMatches[removeMatch == FALSE, ]
    } else if (strand == "+") {
        tirMatches <- tirMatches[tirMatches$start > tsdLength, ]
    }

    return(tirMatches)
}
