#' @title Convert .uc Files to Dataframe
#' @description Reads .uc files (USEARCH Cluster Format) generated by the VSEARCH clustering algorithm.
#' @param file The file path of the .uc file.
#' @author Jack Gisby
#' @return A dataframe, \code{packClusts}, containing the converted .uc file.
#' @export

readUc <- function(file) {
  packClusts <- utils::read.table(file, sep = "\t")
  colnames(packClusts) <- c(
    "type",
    "cluster",
    "width",
    "identity",
    "strand",
    "6",
    "7",
    "cigarAlignment",
    "query",
    "target"
  )

  return(subset(packClusts, select = -c(6, 7)))
}
