#' @title
#' Convert .blast6out Files to Dataframe
#'
#' @description
#' Reads .blast6out files (NCBI Blast Format) generated by 
#' the VSEARCH clustering and alignment algorithms.
#'
#' @param file
#' The file path of the .blast6out file.
#'
#' @return
#' A dataframe containing the converted .blast6out file. 
#' The file contains the following features:
#' \itemize{
#'     \item Query sequence ID
#'     \item Target sequence ID
#'     \item Percenty sequence identity
#'     \item Alignment length
#'     \item Number of mismatches
#'     \item Number of gaps
#'     \item Base position of alignment start 
#'     in query sequence
#'     \item Base position of alignment end in query sequence
#'     \item Base position of alignment start in target sequence
#'     \item Base position of alignment end in target sequence
#'     \item E-value
#'     \item Bit score
#' }
#'
#' @details
#' blast6out file is tab-separated text file compatible with 
#' NCBI BLAST m8 and NCBI BLAST+ outfmt 6 formats. One 
#' cluster/alignment can be found for each line.
#'
#' @seealso
#' de{\link{tirClust}}, code{\link{packAlign}}, 
#' code{\link{readUc}}, code{\link{packClust}}
#'
#' @references
#' VSEARCH may be downloaded from 
#' \url{https://github.com/torognes/vsearch}. See 
#' \url{https://www.ncbi.nlm.nih.gov/pubmed/27781170} 
#' for further information.
#' 
#'
#' @examples 
#' readBlast6Out(system.file(
#'     "extdata", 
#'     "packmatches.blast6out", 
#'     package = "packFinder"
#' ))
#' 
#' @author
#' Jack Gisby
#' 
#' @export

readBlast6Out <- function(file) {
    if (!is.null(file)) {
        if (!(file.access(file, 4) == 0) |
            !(file.access(file, 4) == 0) |
            !(file.access(file, 2) == 0)) {
            stop("file does not exist, or R 
                does not have read/write permissions")
        }
    }

    blast6out <- utils::read.table(file, sep = "\t")
    colnames(blast6out) <- c(
        "query",
        "subject",
        "identity",
        "width",
        "mismatch",
        "openGaps",
        "queryStart",
        "queryEnd",
        "targetStart",
        "targetEnd",
        "e",
        "bits"
    )

    return(blast6out)
}
