#' @title Convert .uc Files to Dataframe
#' @description Reads .uc files (USEARCH Cluster Format) generated by the VSEARCH clustering algorithm.
#' @param savePath The file path of the .uc file.
#' @author Jack Gisby
#' @return A dataframe, \code{packClusts}, containing the converted .uc file.
#' @export

readUc <- function(savePath) {
  packClusts <- read.table(savePath, sep = "\t")
  colnames(packClusts) <- c("type",
                            "cluster",
                            "width",
                            "identity",
                            "strand",
                            "6",
                            "7",
                            "cigarAlignment",
                            "query",
                            "target"
  )

  packClusts %>%
    dplyr::select(-c("6", "7")) %>%
    return()
}
